spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    root: warn
    com.li.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'